# Generated by Django 3.2.15 on 2023-03-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0012_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
