# Generated by Django 3.2.15 on 2023-04-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
